### ISSUE TITLE
When accessing image picker the music stops playing

### ISSUE THREAD

**Issue by radimhalfar** [inloop/image-picker#20]
Steps to reproduce:
1. Play music on iPhone 
2. Enable Video and Photo for ImagePicker
3. Go to app and open image picker 

Result: Music stops playing due to AVCAptureSession audio type 

Provide different session setups for image, video, live photos.

**Comment by tankista** [comment]
@radimhalfar sounds legit to me, what is expected behaviour?

**Comment by radimhalfar** [comment]
Ok, started to work right now. Closing it as unnecessary fix.
