### ISSUE TITLE
Crash in ImagePickerController

### ISSUE THREAD

**Issue by radimhalfar** [inloop/image-picker#21]
From Fabric:
![fabric_issue](https://user-images.githubusercontent.com/14109333/32596051-4625019e-c532-11e7-8b5f-37e4490df7d6.png)

Fatal Exception: NSInternalInconsistencyException
attempt to delete and reload the same index path (<NSIndexPath: 0x1d4429640> {length = 2, path = 2 - 5})

**Comment by tankista** [comment]
@radimhalfar feel free to provide me steps to reproduce or any kind of information

**Comment by radimhalfar** [comment]
Will check it out if it occurs again, right now I do not have the steps to reproduce, but will attach a crash log from device directly. It appears it is under iOS 10.3.3 and iPhone 5s

**Comment by radimhalfar** [comment]
Please check the crash log. 

Steps to reproduce are:
Open ImagePickerController
On cell with camera in picker switch camera to front 
Take picture

Result: App crashes 
Environment: iOS 10.3.3, iPhone 5s

[Loop  9.11.17 15-28.crash.zip](https://github.com/inloop/image-picker/files/1460563/Loop.9.11.17.15-28.crash.zip)
