### ISSUE TITLE
How to get photo/Video captured from camera picker

### ISSUE THREAD

**Issue by SwiftySrl2** [inloop/image-picker#25]
I got implement your image picker, i'm able to bring object from collection, but when i click "camera" button that allow me to have a default camera of smartphone, after clicked to get foto or video, i'm not able to find that file in a list....where i can find that, there is a delegate that allow to get that file ?

**Comment by radimhalfar** [comment]
Hi, exactly as you wrote, there is a delegate call. Try to use this delegate function and let me know if it helps. 

https://github.com/inloop/image-picker/blob/cd59ef9163fe197b33bbcdd8f8a55eeaddb109bd/ImagePicker/ImagePickerController.swift#L36

**Comment by SwiftySrl2** [comment]
That delegate is called when i capture or select pics in the collection of the image piker, but if i want do a picture or a video from default camera iPhone (mean when i click button "camera"), the delegate will not called

**Comment by tankista** [comment]
@SwiftySrl2 when you tap on any action item, implementation of the library will only notify you as it's consumer that this button has been tapped. In fact, it's your responsibility to present UIImagePickerController, thus you have to assign your own delegate and handle it on your own. 

The reason why this is not handled by the library is that library provides you only opportunity to add there any custom action items you wish. In this example app I implemented default Camera and Image pickers. I hope this will help to resolve your issue.

**Comment by SwiftySrl2** [comment]
Great solution! Thank you!
