### ISSUE TITLE
Deselcted cells after taking a picture

### ISSUE THREAD

**Issue by SwiftySrl2** [inloop/image-picker#26]
Hi,
i got a problem when i take a picture, in my collection that pics will added but the already selected cells will be deselected (it seems that this collection reloaded itself).
Im using default cells and layout  (not that custom one)
I did a test with your example app, and i noticed that this not happen.

Can u please tell me how can i move to solve this ?

**Comment by tankista** [comment]
hi, can you provide more information? Perhaps what configuration do you use?

**Comment by SwiftySrl2** [comment]
This is my configuration:

        let imagePicker = ImagePickerController()
        imagePicker.delegate = self
        imagePicker.dataSource = self
        imagePicker.captureSettings.cameraMode = .photo
        imagePicker.captureSettings.savesCapturedPhotosToPhotoLibrary = true
        imagePicker.layoutConfiguration.numberOfAssetItemsInRow = 2
        imagePicker.layoutConfiguration.scrollDirection = .vertical
        imagePicker.layoutConfiguration.showsSecondActionItem = false
        imagePicker.layoutConfiguration.interitemSpacing = 5
        imagePicker.layoutConfiguration.actionSectionSpacing = 5
        imagePicker.layoutConfiguration.cameraSectionSpacing = 5
        imagePicker.assetsFetchResultBlock = {
            guard let collection = PHAssetCollection.fetchAssetCollections(with: .smartAlbum, subtype: .smartAlbumGeneric, options: nil).firstObject else {
                return nil
            }
            return PHAsset.fetchAssets(in: collection, options: nil)
        }
       self.presentPickerModally(imagePicker)


Do you need more information?

**Comment by tankista** [comment]
I see the problem, it's a bug. Which branch do you use? `develop` or `master`?

**Comment by SwiftySrl2** [comment]
How can i understand which one i'm using?

**Comment by tankista** [comment]
Problem is that when incremental updates on collection view (animations) were replaced by reloadData(), it collectionView does not preserve selected items. Therefore they are deselected when collection view is updated. I had to put back code that did incremental animations, and tried to fix problem when it crashed. 

@SwiftySrl2 please try to checkout this branch  `feature/fix_unselecting_cells_when_reloaded` and let me know if it works for you.

**Comment by SwiftySrl2** [comment]
Hi,
Sorry but i didn't get clearly the modify that u suggest to me just because i don't know your code properly.

Can u please guide trough giving to me the class and the changes that i need to implement ??

**Comment by tankista** [comment]
@SwiftySrl2 I want you to try the latest change I made on this git branch `feature/fix_unselecting_cells_when_reloaded` if it works. If you are using Carthage for dependencies, you will have to specify this branch in your cartfile. If you are using submodules, checkout this branch and if you are copy-pasting the code, copy the one from this branch. Let me know if you need any further assistance.

**Comment by tankista** [comment]
this issue has been resolved and merged to develop.

**Comment by SwiftySrl2** [comment]
sorry dev but I can not update your new branch in my project. I install the code through carthage, can you help me do this?

**Comment by SwiftySrl2** [comment]
I managed to implement it! Now it works. Thank you

**Comment by tankista** [comment]
@SwiftySrl2 I am going to create new master release within 10 minutes, you can then switch to latest official release.
