### ISSUE TITLE
Add support for custom cell identifiers when defining CustomCell for any action. 

### ISSUE THREAD

**Issue by radimhalfar** [inloop/image-picker#3]
Options:
- add support for custom identifier
- add static overridable identifier to cells 
- expose identifiers that everyone is aware of it

or update readme defining that the reuse identifier should be left empty when registering the nib

**Comment by tankista** [comment]
It is a programmer's error to set custom cell identifier to custom nibs. Image Picker is handling cell management internally. I updated documentation with this issue.
