### ISSUE TITLE
ImagePickerController.appearance().backgroundColor = UIColor.black does not work

### ISSUE THREAD

**Issue by radimhalfar** [inloop/image-picker#5]
If setting any color to appearance globally, it does not work. 

Steps to reproduce: 
1. call ImagePickerController.appearance().backgroundColor = UIColor.black
2. create an instance of ImagePickerController
3. present it as input view 

Expected result: 
- the background color is black 

Actual result:
The color is not changes 

Environment:
iPhone 6s
iOS 11.0

Note: Setting the background per instance works well

**Comment by tankista** [comment]
setting global appearance must be done *before* an instance is presented. Setting appearance after will have no effect.
