### ISSUE TITLE
'State' enum is ambiguous (iOS 12)

### ISSUE THREAD

**Issue by miasma13** [inloop/image-picker#51]
When built with iOS 12 beta SDK the `State` enum conflicts with the `UIControl.State` (renamed from `UIControlState` in iOS 12).

https://github.com/inloop/image-picker/blob/cabbc4f4ec41ca83a046a053686e294335ef8f3f/ImagePicker/RecordButton.swift#L50

**Comment by tankista** [comment]
this should be fixed in latest `master`
