### ISSUE TITLE
Swift 4.2/Xcode 10/iOS 12 compatibility 

### ISSUE THREAD

**Issue by abubakhr** [inloop/image-picker#52]
Receive following error. 
Module compiled with Swift 4.1.2 cannot be imported by the Swift 4.2 compiler: .../Carthage/Build/iOS/ImagePicker.framework/Modules/ImagePicker.swiftmodule/arm64.swiftmodule

Have already tried: ``` carthage update --platform iOS``` and ``` carthage build```

log information:
```
The following build commands failed:
	CompileSwift normal armv7
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
	CompileSwift normal arm64
(3 failures)
```

Also tried setting different Swift Language Versions in Build Settings

Nothing helps

**Comment by tankista** [comment]
@abubakhr please try to rebuild with latest `master` and let me know if it fixed the problem.

**Comment by abubakhr** [comment]
@tankista the problem is fixed, closing the issue
